### ISSUE TITLE
Input ../cluster_data/pdb_trimmed_seqs.fasta does not exist

### ISSUE THREAD

**Issue by adrienchaton** [meilerlab/HyperMPNN#2]
Hello and sorry if I again overlooked something.

I followed all the well detailed steps from your ```mpnn_retrain_docu```, no issues until running ```bash 3_clustering.sh```.

When calling the clustering script, mmseqs complains.

```Input ../cluster_data/pdb_trimmed_seqs.fasta does not exist```

This is due because actually there is no ```pdb_trimmed``` directory from which the input fasta should be created.
And I didn't find any step which is responsible for creating this folder and filling it with pdb files...

Right now I proceeded with running the clustering on the pdb files I put in ```input_pdb```, the script is currently running.

Did I miss any step? Or is it fine if I just replace ```pdb_trimmed``` with ```input_pdb```?

Thanks for sharing your work!

**Comment by adrienchaton** [comment]
I could go through and start training a model, loss behaves well, again thanks for your valuable sharing of retraining MPNN from predicted structures 🙌

Again, apologises if I may have overlooked some details but there was another path which caused errors so I'll leave it here in case that helps. Since I copied ```input_pdb``` in place of ```pdb_trimmed```, then mmseqs output a result table called ```pdb_trimmed_seqs_cluster.tsv``` whereas ```create_cluster_lists.py``` receives ```myinput_cluster.tsv``` as argument.

For later I need to dig into training with multimer/complex pdb inputs.. Do you have plans in this directions?

**Comment by Bloeci** [comment]
Hi,
I'm sorry for the inconsistencies, but you were right. In the original version, the input pdbs were in the path `pdb_trimmed` because we cleaned up low-confidence N-/C-terminal areas as described in the paper.

I have adjusted scripts 2 and 3 regarding this error. As you said, **replacing** `pdb_trimmed` with `input_pdb` solves the problem. I have also adopted the name of the fasta in script 3 for the generation of the cluster files. If something does not work, please let me know.

And many thanks for the words. It means a lot to me/us.

---

Regarding your last question: since we currently only use Alphafold structures from the database, which only contains single chains, we are not planning to extend it to multimer/complex pdbs. But, of course, that is an option. If there is time in the future, I will consider it.

**Comment by adrienchaton** [comment]
Thanks for the confirmation! That makes sense, I just wanted to be sure I didn't miss a step or whatsoever but overall it looked good.
